### ISSUE TITLE
`converter.sqlToJson` increase the node process to 50% usage

### ISSUE THREAD

**Issue by steevepay** [Dobby85/hearthjs#13]
On a large SQL dataset, `sqlToJson` is increasing the node process to 50% usage and blocking everything else
https://github.com/Dobby85/hearthjs/blob/f8bff8e5813509e497524532e07f257e9d1603d8/lib/converter.js#L9

**Comment by Dobby85** [comment]
The problem should be fixed with the version 4.0.0 of hearthjs I just release! On the dataset I used, the execution time of the function has been improved up to 80% !

Let me know if you still have the problem with the new version 😊

**Comment by steevepay** [comment]
I'll try the new version asap, thank you @Dobby85 !
